name: CI

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  test:
    strategy:
      matrix:
        go: [1.16, 1.20, "stable"]
    name: Go ${{ matrix.go }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Go ${{ matrix.go }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}

      - name: Run Tests
        run: go test ./...

  benchmark:
    needs: test
    name: Benchmark comparison
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code (Old)
        uses: actions/checkout@v4
        with:
          ref: ${{ github.base_ref }}
          path: old

      - name: Checkout Code (New)
        uses: actions/checkout@v4
        with:
          path: new

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "stable"

      - name: Install Dependencies
        run: go install golang.org/x/perf/cmd/benchstat@latest

      - name: Run Benchmark (Old)
        run: |
          cd old
          go test -run="-" -bench="." ./... > benchmark.txt

      - name: Run Benchmark (New)
        run: |
          cd new
          go test -run="-" -bench="." ./... > benchmark.txt

      - name: Run Benchstat
        run: benchstat old/benchmark.txt new/benchmark.txt
